image: maven:3.6.3

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile install -DskipTests -e

test:
  stage: test
  script:
    - mvn test
